Models/ErrorViewModel.cs
using System;

namespace TrabajoIntegrador.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Publicacion.cs
using System.Collections.Generic;

namespace TrabajoIntegrador.Models
{
    public class Publicacion
    {
        //A su vez, también debe poder crearse Publicaciones (Tienen un ID, titulo, descripción, precio y nombre del vendedor), deben ser almacenadas en una lista.
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public string EmailVendedor { get; set; }
        public string NombreVendedor { get; set; }

        public static List<Publicacion> publicaciones = new List<Publicacion>();
        public static int contID = 0;

        public static List<Publicacion> busquedaVendedor = new List<Publicacion>();

    }
}

Models/Usuario.cs
using System.Collections.Generic;

namespace TrabajoIntegrador.Models
{
    public class Usuario
    {
        //Deben poder crearse Usuarios los cuales tienen un nombre de usuario, una contraseña, un email, y un tipo(Vendedor o Cliente), estos deben ser almacenados en una lista.
        public string Nombre { get; set; }
        public string Contrasena { get; set; }
        public string Email { get; set; }
        public string Tipo { get; set; }

        public static List<Usuario> usuarios = new List<Usuario>();

        public static Usuario usuarioActual = null;

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TrabajoIntegrador.Models;

namespace TrabajoIntegrador.Controllers
{
    public class HomeController : Controller
    {
        

        public IActionResult Index()
        {
            Publicacion.busquedaVendedor.Clear();
            return View();
        }

        public IActionResult BuscarVendedor(string barraBusqueda)
        {
            if (barraBusqueda == null)
            {
                return View("Index");
            }
            string busqueda = barraBusqueda.Trim().ToLower();
            IEnumerable<Publicacion> resultado = from p in Publicacion.publicaciones where p.NombreVendedor.ToLower().Trim().Contains(busqueda) || p.EmailVendedor.ToLower().Trim().Contains(busqueda) select p;
            Publicacion.busquedaVendedor = resultado.ToList();
            return View("Index");
        }

        public IActionResult Reset()
        {
            Publicacion.busquedaVendedor.Clear();
            return View("Index");
        }


        

    }
}

Controllers/PublicacionesController.cs
using Microsoft.AspNetCore.Mvc;
using TrabajoIntegrador.Models;

namespace TrabajoIntegrador.Controllers
{
    public class PublicacionesController : Controller
    {
        public IActionResult CrearPublicacion()
        {
            return View();
        }

        public IActionResult VerPublicaciones()
        {
            return View();
        }


        public IActionResult CrearP(string titulo, string descripcion, decimal precio)
        {
            ViewBag.PublicacionCreada = "";
            Publicacion p = new Publicacion();
            p.Titulo = titulo.Trim();
            p.Descripcion = descripcion.Trim();
            p.Precio = precio;
            p.EmailVendedor = Usuario.usuarioActual.Email;
            p.NombreVendedor = Usuario.usuarioActual.Nombre;

            Publicacion.contID = Publicacion.contID + 1;

            p.Id = Publicacion.contID;

            Publicacion.publicaciones.Add(p);

            ViewBag.PublicacionCreada = "Se creo una publicacion";
            return View("VerPublicaciones");
        }


    }
}

Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using TrabajoIntegrador.Models;
using System;
using System.Linq;
using System.Collections.Generic;


namespace TrabajoIntegrador.Controllers
{
    public class UsuariosController : Controller
    {
        public IActionResult IniciarSesion()
        {
            return View();
        }

        public IActionResult Registrarse()
        {
            return View();
        }


        
        public IActionResult CrearUsuario(string nombreUsuario, string contrasena, string email, string tipo)
        {
            ViewBag.ErrorUsuario = "";
            Usuario u = new Usuario();
            u.Nombre = nombreUsuario.Trim();
            u.Contrasena = contrasena.Trim();
            u.Email = email.Trim();
            u.Tipo = tipo;

            IEnumerable<Usuario> usuario = Usuario.usuarios.Where(u => u.Email == email);
            if (usuario.ToList().Count > 0)
            {
                ViewBag.ErrorUsuario = "El usuario ya existe";
                return View("Registrarse");
            }

            Usuario.usuarios.Add(u);
            Usuario.usuarioActual = u;


            return RedirectToAction("Index", "Home");
        }

        public IActionResult Iniciar(string email, string contrasena)
        {
            Usuario us = new Usuario();
            ViewBag.ErrorContrasena = "";
            ViewBag.ErrorMail = "";

            IEnumerable<Usuario> usuario = Usuario.usuarios.Where(u => u.Email == email);
            if(usuario == null || usuario.ToList().Count == 0)
            {
                ViewBag.ErrorMail = "El usuario no existe";
                return View("IniciarSesion");
            }
            foreach (Usuario u in usuario)
            {
                us = u;
            }

            if (us.Contrasena == contrasena)
            {
                Usuario.usuarioActual = us;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ErrorContrasena = "La contraseña es incorrecta";
                return View("IniciarSesion");
            }


        }

        public IActionResult CerrarSesion()
        {
            Usuario.usuarioActual = null;
            return RedirectToAction("Index", "Home");
        }


    }

}

Views/Home/Index.cshtml
<div class="d-flex flex-column mt-3">
    @if(Publicacion.publicaciones.Count == 0)
    {
        <p class="h1">Bienvenido</p>
        <p class="h2">Todas las publicaciones apareceran aqui</p>
    } 
    else
    {

        <p class="h1 p-2 mb-3 ">Todas las publicaciones</p>

        <div class="d-flex">
            <form action="@Url.Action("BuscarVendedor", "Home")" class="d-flex  mb-3">
                <input name="barraBusqueda" type="text" placeholder="Buscar vendedor" class="form-control input-buscar" />
                <input type="submit" value="Buscar" class="btn btn-primary ml-2" />
            </form>
            <button class="btn btn-danger h-25 ml-1" onclick="location.href='@Url.Action("Reset", "Home")'">Deshacer</button>
        </div>
        
        
        

        <div class="d-flex flex-wrap  publicaciones">
            @if(Publicacion.busquedaVendedor.Count != 0)
            {
                @foreach(Publicacion p in Publicacion.busquedaVendedor)
                {   

                IEnumerable<Usuario> usuario = Usuario.usuarios.Where(u => u.Email == p.EmailVendedor);
                string usu = "";
                foreach(Usuario u in usuario)
                {
                    usu = u.Nombre;
                }


                <div class="card publicacion">
                  <div class="card-header text-white d-flex justify-content-between header"><p class="my-auto pre-publicacion font-weight-bold">$@p.Precio</p> <p class="my-auto font-weight-bold">ID: @p.Id</p> <p class="my-auto font-weight-bold usu-publicacion">@usu</p></div>
                  <div class="card-body">
                    <h5 class="card-title titulo font-weight-bold">@p.Titulo</h5>
                    
                    <p class="card-text descripcion">@p.Descripcion</p>
                    
                  </div>
                </div>
                }
            }

            else
            {
                @foreach(Publicacion p in Publicacion.publicaciones)
                {   

                IEnumerable<Usuario> usuario = Usuario.usuarios.Where(u => u.Email == p.EmailVendedor);
                string usu = "";
                foreach(Usuario u in usuario)
                {
                    usu = u.Nombre;
                }



                <div class="card publicacion">
                  <div class="card-header text-white d-flex justify-content-between header"><p class="my-auto pre-publicacion font-weight-bold">$@p.Precio</p> <p class="my-auto font-weight-bold">ID: @p.Id</p> <p class="my-auto font-weight-bold usu-publicacion">@usu</p></div>
                  <div class="card-body">
                    <h5 class="card-title titulo font-weight-bold">@p.Titulo</h5>
                    
                    <p class="card-text descripcion">@p.Descripcion</p>
                    
                  </div>
                </div>
                }
            }
        </div>
    }
        
</div>

<style>

    .publicaciones{
        width: 90%;
        
    }

    .input-buscar{
        width: 600px;
    }

    .card-header{
        background-color: #396EB0;
    }
    
    .publicacion{
        height: 300px;
        width: 300px;
        margin: 15px;
        
    }

    .header{
        height: 55px;
        
    }


    .titulo{
        overflow: hidden;
        display: -webkit-box;
        text-overflow: ellipsis;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        height: 50px;
        color: #1363DF;
    }

    .descripcion{
        overflow: hidden;
        display: -webkit-box;
        text-overflow: ellipsis;
        -webkit-line-clamp: 5;
        -webkit-box-orient: vertical;
        max-width: 200px;
    }

    .h1{
        color: #1363DF;
    }

    .usu-publicacion{
        width: 100px;
        text-align: end;
        overflow: hidden;
        text-overflow: ellipsis;
        height: 24px;
    }

    .pre-publicacion{
        width: 100px;
    }

    

</style>

Views/Publicaciones/CrearPublicacion.cshtml
<div>
    <p class="h1">Crear Publicacion</p>

    <form action="@Url.Action("CrearP", "Publicaciones")" class="w-75">
        <div class="form-group mt-4">
            <label>Titulo</label>
            <input name="titulo" required type="text" class="form-control" placeholder="Titulo" />
        </div>

        <div class="form-group">
            <label>Descripcion</label>
            <input name="descripcion" required type="text" class="form-control" placeholder="Descripcion" />
        </div>

        <div class="form-group">
            <label>Precio</label>
            <input name="precio" min="0" required max="10000000" step=".01" type="number" class="form-control" placeholder="Precio" />
        </div>


        <input type="submit" value="Crear Publicacion" class="btn btn-primary" />
    </form>

</div>

<style>
    .h1{
        color: #1363DF;
    }
</style>

Views/Publicaciones/VerPublicaciones.cshtml
@if(ViewBag.PublicacionCreada != null && ViewBag.PublicacionCreada != "")
{
    <script type="text/javascript">  
        window.onload = function () {  
            alert("@ViewBag.PublicacionCreada");  
        };  
    </script>  
}

<div>
    @{
        IEnumerable<Publicacion> publicacionesVendedor = Publicacion.publicaciones.Where(p => p.EmailVendedor == Usuario.usuarioActual.Email);
        if(publicacionesVendedor.ToList().Count == 0)
        {
                    <p class="h2">No publicó nada</p>
        }
        else
        {
                    <p class="h1 p-2 mb-3 mt-3 ">Mis publicaciones</p>
                    <div class="d-flex flex-wrap  publicaciones">
                    @foreach(Publicacion p in publicacionesVendedor)
            {

                        <div class="card publicacion">
                          <div class="card-header text-white d-flex justify-content-between header"><p class="my-auto">$@p.Precio</p> <p class="my-auto font-weight-bold">ID: @p.Id</p></div>
                          <div class="card-body">
                            <h5 class="card-title titulo">@p.Titulo</h5>
                            <p class="card-text descripcion">@p.Descripcion</p>
                            
                          </div>
                        </div>
            }
                    </div>
        }
    }
</div>
<style>

    .publicacion{
        height: 300px;
        width: 300px;
        margin: 15px;
    }

    .header{
        height: 55px;
    }

    .card-header{
        background-color: #396EB0;
    }

    .titulo{
        overflow: hidden;
        display: -webkit-box;
        text-overflow: ellipsis;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        height: 50px;
        color: #1363DF;
    }


    .descripcion{
        overflow: hidden;
        display: -webkit-box;
        text-overflow: ellipsis;
        -webkit-line-clamp: 5;
        -webkit-box-orient: vertical;
        max-width: 200px;
    }


    .h1{
        color: #1363DF;
    }


    

</style>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trabajo Integrador</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="body">
    <header>
        <nav class="barra navbar navbar-expand-sm navbar-toggleable-sm text-white   border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trabajo Integrador</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 ml-4">
                        @if(Usuario.usuarioActual != null && Usuario.usuarioActual.Tipo == "vendedor")
                        {
                            <li class="nav-item border-right pr-1">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>

                            <li class="nav-item border-right pl-1 pr-1">
                                <a class="nav-link text-white" asp-area="" asp-controller="Publicaciones" asp-action="CrearPublicacion">Crear Publicacion</a>
                            </li>

                            <li class="nav-item ml-1 pl-1">
                                <a class="nav-link text-white" asp-area="" asp-controller="Publicaciones" asp-action="VerPublicaciones">Mis Publicaciones</a>
                            </li>
                        }
                        
                    </ul>
                    @if(Usuario.usuarioActual == null)
                    {
                        <div>
                            <button class="btn btn-info" onclick=location.href='@Url.Action("IniciarSesion", "Usuarios")'>Iniciar Sesion</button>
                            <button class="btn btn-primary" onclick=location.href='@Url.Action("Registrarse", "Usuarios")'>Registrarse</button>
                        </div>
                    }
                    else
                    {
                        <div class="d-flex ">
                            <p class="mr-3 my-auto nombre">@Usuario.usuarioActual.Nombre</p>
                            <button class="btn btn-danger" onclick=location.href='@Url.Action("CerrarSesion", "Usuarios")'>Cerrar Sesion</button>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Trabajo Integrador</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<style>
    .body{
        background-color: #DFF6FF;
    }

    .barra{
        background-color: #1F4690;
        color: white;
    }

    .navbar-brand{
        color: #DFF6FF;
        font-weight: bold;
    }
    .navbar-brand:hover{
        color: #47B5FF;

    }

    .nombre{
        width: 100px;
        overflow: hidden;
        text-overflow: ellipsis;
        text-align: end;
    }
</style>

Views/Usuarios/IniciarSesion.cshtml
<div>
    <p class="h1">Iniciar Sesion</p>

    <form action="@Url.Action("Iniciar", "Usuarios")" class="w-75">
        <div class="form-group mt-4">
            <label>Email</label>
            <input name="email" type="email" class="form-control" placeholder="Email" />
            <label>@ViewBag.ErrorMail</label>
        </div>
        <div class="form-group">
            <label>Contraseña</label>
            <input required name="contrasena" type="text" class="form-control" placeholder="Contraseña" />
            <label>@ViewBag.ErrorContrasena</label>
        </div>

        <input type="submit" value="Iniciar Sesion" class="btn btn-primary" />
    </form>

</div>

<style>
    .h1{
        color: #1363DF;
     }
</style>

Views/Usuarios/Registrarse.cshtml
<div>
    <p class="h1">Registrarse</p>

    <form action="@Url.Action("CrearUsuario", "Usuarios")" class="w-75">
        <p>@ViewBag.ErrorUsuario</p>
        <div class="form-group mt-4">
            <label>Nombre de usuario</label>
            <input name="nombreUsuario" required type="text" class="form-control" placeholder="Nombre de usuario" />
        </div>

        <div class="form-group">
            <label>Contraseña</label>
            <input name="contrasena" required type="text" class="form-control" placeholder="Contraseña" />
        </div>

        <div class="form-group">
            <label>Email</label>
            <input name="email" required type="email" class="form-control" placeholder="Email" />
        </div>

        <div class="form-group">
            <label>Tipo de usuario</label>
            <select name="tipo" required class="custom-select">
                <option value="" disabled selected="true">-- Seleccione un tipo de usuario --</option>
                <option value="cliente">Cliente</option>
                <option value="vendedor">Vendedor</option>
            </select>
        </div>

        <input type="submit" value="Registrarse" class="btn btn-primary" />
    </form>

</div>

<style>
    .h1{
        color: #1363DF;
    }

</style>